[2025-02-12T09:17:04.250+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-12T09:17:04.300+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.load.transform_fact_orders scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T09:17:04.316+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.load.transform_fact_orders scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T09:17:04.317+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-12T09:17:04.337+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load.transform_fact_orders> on 2025-02-11 00:00:00+00:00
[2025-02-12T09:17:04.343+0000] {standard_task_runner.py:63} INFO - Started process 237 to run task
[2025-02-12T09:17:04.348+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'load.transform_fact_orders', 'scheduled__2025-02-11T00:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpcmej5_yo']
[2025-02-12T09:17:04.351+0000] {standard_task_runner.py:91} INFO - Job 204: Subtask load.transform_fact_orders
[2025-02-12T09:17:04.422+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.load.transform_fact_orders scheduled__2025-02-11T00:00:00+00:00 [running]> on host 1f90b0c5673e
[2025-02-12T09:17:04.562+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='load.transform_fact_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-11T00:00:00+00:00'
[2025-02-12T09:17:04.564+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-12T09:17:04.593+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:17:04.671+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:17:04.744+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:17:04.826+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:17:06.029+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:17:06.127+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:17:07.372+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:17:07.548+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:17:08.169+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:17:08.272+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:17:09.498+0000] {logging_mixin.py:188} INFO - Các cột trong DataFrame sau khi merge:
[2025-02-12T09:17:09.500+0000] {logging_mixin.py:188} INFO - Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'customer_zip_code_prefix'],
      dtype='object')
[2025-02-12T09:17:10.045+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:17:21.522+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào fact_orders
[2025-02-12T09:17:21.622+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-12T09:17:21.623+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-12T09:17:21.636+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=load.transform_fact_orders, run_id=scheduled__2025-02-11T00:00:00+00:00, execution_date=20250211T000000, start_date=20250212T091704, end_date=20250212T091721
[2025-02-12T09:17:21.707+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-12T09:17:21.733+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T09:17:21.736+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
