[2025-02-12T09:31:53.256+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-12T09:31:53.287+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.load.transform_fact_orders manual__2025-02-12T09:30:31.798632+00:00 [queued]>
[2025-02-12T09:31:53.296+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.load.transform_fact_orders manual__2025-02-12T09:30:31.798632+00:00 [queued]>
[2025-02-12T09:31:53.297+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-12T09:31:53.312+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load.transform_fact_orders> on 2025-02-12 09:30:31.798632+00:00
[2025-02-12T09:31:53.317+0000] {standard_task_runner.py:63} INFO - Started process 259 to run task
[2025-02-12T09:31:53.320+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'load.transform_fact_orders', 'manual__2025-02-12T09:30:31.798632+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmppfrv2eu_']
[2025-02-12T09:31:53.322+0000] {standard_task_runner.py:91} INFO - Job 237: Subtask load.transform_fact_orders
[2025-02-12T09:31:53.368+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.load.transform_fact_orders manual__2025-02-12T09:30:31.798632+00:00 [running]> on host 18b9093ce731
[2025-02-12T09:31:53.570+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='load.transform_fact_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T09:30:31.798632+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T09:30:31.798632+00:00'
[2025-02-12T09:31:53.571+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-12T09:31:53.587+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:31:53.641+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:31:53.694+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:31:53.745+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:31:54.487+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:31:54.554+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:31:55.388+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:31:55.453+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:31:55.843+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:31:55.906+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:31:56.557+0000] {logging_mixin.py:188} INFO - Các cột trong DataFrame sau khi merge:
[2025-02-12T09:31:56.559+0000] {logging_mixin.py:188} INFO - Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'customer_zip_code_prefix'],
      dtype='object')
[2025-02-12T09:31:56.877+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:32:04.660+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào fact_orders
[2025-02-12T09:32:04.729+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-12T09:32:04.730+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-12T09:32:04.741+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=load.transform_fact_orders, run_id=manual__2025-02-12T09:30:31.798632+00:00, execution_date=20250212T093031, start_date=20250212T093153, end_date=20250212T093204
[2025-02-12T09:32:04.821+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-12T09:32:04.838+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T09:32:04.843+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
