[2025-02-12T09:35:45.734+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-12T09:35:45.775+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_customers manual__2025-02-12T09:34:47.843170+00:00 [queued]>
[2025-02-12T09:35:45.787+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_customers manual__2025-02-12T09:34:47.843170+00:00 [queued]>
[2025-02-12T09:35:45.788+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-12T09:35:45.807+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_customers> on 2025-02-12 09:34:47.843170+00:00
[2025-02-12T09:35:45.817+0000] {standard_task_runner.py:63} INFO - Started process 247 to run task
[2025-02-12T09:35:45.823+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_customers', 'manual__2025-02-12T09:34:47.843170+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpe4czo19o']
[2025-02-12T09:35:45.827+0000] {standard_task_runner.py:91} INFO - Job 244: Subtask transform.transform_dim_customers
[2025-02-12T09:35:45.894+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_customers manual__2025-02-12T09:34:47.843170+00:00 [running]> on host 6d14b9bebf01
[2025-02-12T09:35:46.287+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T09:34:47.843170+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T09:34:47.843170+00:00'
[2025-02-12T09:35:46.288+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-12T09:35:46.321+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:35:46.460+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:35:46.592+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:35:46.798+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:35:48.736+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:35:55.294+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào dim_customers
[2025-02-12T09:35:55.309+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-12T09:35:55.310+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-12T09:35:55.319+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_customers, run_id=manual__2025-02-12T09:34:47.843170+00:00, execution_date=20250212T093447, start_date=20250212T093545, end_date=20250212T093555
[2025-02-12T09:35:55.352+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-12T09:35:55.372+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-12T09:35:55.375+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
