[2025-02-12T10:02:44.796+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-12T10:02:44.845+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_geolocation manual__2025-02-12T10:01:53.320861+00:00 [queued]>
[2025-02-12T10:02:44.873+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_geolocation manual__2025-02-12T10:01:53.320861+00:00 [queued]>
[2025-02-12T10:02:44.875+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-12T10:02:44.903+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_geolocation> on 2025-02-12 10:01:53.320861+00:00
[2025-02-12T10:02:44.914+0000] {standard_task_runner.py:63} INFO - Started process 329 to run task
[2025-02-12T10:02:44.925+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_geolocation', 'manual__2025-02-12T10:01:53.320861+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmparho8z_5']
[2025-02-12T10:02:44.930+0000] {standard_task_runner.py:91} INFO - Job 259: Subtask transform.transform_dim_geolocation
[2025-02-12T10:02:45.017+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_geolocation manual__2025-02-12T10:01:53.320861+00:00 [running]> on host 0cefc44a17d0
[2025-02-12T10:02:45.191+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_geolocation' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T10:01:53.320861+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T10:01:53.320861+00:00'
[2025-02-12T10:02:45.193+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-12T10:02:45.503+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:45.667+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:45.822+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:46.008+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T10:02:53.846+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:54.814+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào dim_geolocation
[2025-02-12T10:02:54.839+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-12T10:02:54.840+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-12T10:02:54.853+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_geolocation, run_id=manual__2025-02-12T10:01:53.320861+00:00, execution_date=20250212T100153, start_date=20250212T100244, end_date=20250212T100254
[2025-02-12T10:02:54.895+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-12T10:02:54.932+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T10:02:54.935+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
