[2025-02-12T09:27:45.551+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-12T09:27:45.584+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.load.transform_fact_orders manual__2025-02-12T09:26:29.698226+00:00 [queued]>
[2025-02-12T09:27:45.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.load.transform_fact_orders manual__2025-02-12T09:26:29.698226+00:00 [queued]>
[2025-02-12T09:27:45.595+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-12T09:27:45.612+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load.transform_fact_orders> on 2025-02-12 09:26:29.698226+00:00
[2025-02-12T09:27:45.617+0000] {standard_task_runner.py:63} INFO - Started process 258 to run task
[2025-02-12T09:27:45.621+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'load.transform_fact_orders', 'manual__2025-02-12T09:26:29.698226+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpsuuyfn8k']
[2025-02-12T09:27:45.624+0000] {standard_task_runner.py:91} INFO - Job 228: Subtask load.transform_fact_orders
[2025-02-12T09:27:45.675+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.load.transform_fact_orders manual__2025-02-12T09:26:29.698226+00:00 [running]> on host b9038849bf8a
[2025-02-12T09:27:45.901+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='load.transform_fact_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T09:26:29.698226+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T09:26:29.698226+00:00'
[2025-02-12T09:27:45.902+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-12T09:27:45.920+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:27:46.086+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:27:46.148+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:27:46.212+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:27:47.255+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:27:47.321+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:27:48.306+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:27:48.373+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:27:48.786+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:27:48.855+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T09:27:49.687+0000] {logging_mixin.py:188} INFO - Các cột trong DataFrame sau khi merge:
[2025-02-12T09:27:49.689+0000] {logging_mixin.py:188} INFO - Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'customer_zip_code_prefix'],
      dtype='object')
[2025-02-12T09:27:50.114+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T09:27:58.665+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào fact_orders
[2025-02-12T09:27:58.733+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-12T09:27:58.734+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-12T09:27:58.744+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=load.transform_fact_orders, run_id=manual__2025-02-12T09:26:29.698226+00:00, execution_date=20250212T092629, start_date=20250212T092745, end_date=20250212T092758
[2025-02-12T09:27:58.802+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-12T09:27:58.818+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T09:27:58.821+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
